//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N11Lib.ProductStockService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.n11.com/ws/schemas", ConfigurationName="ProductStockService.ProductStockServicePort")]
    public interface ProductStockServicePort {
        
        // CODEGEN: Generating message contract since the operation DeleteAndUpdateStockByStockAttributes is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        N11Lib.ProductStockService.DeleteAndUpdateStockByStockAttributesResponse1 DeleteAndUpdateStockByStockAttributes(N11Lib.ProductStockService.DeleteAndUpdateStockByStockAttributesRequest1 request);
        
        // CODEGEN: Generating message contract since the operation UpdateStockByStockId is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        N11Lib.ProductStockService.UpdateStockByStockIdResponse1 UpdateStockByStockId(N11Lib.ProductStockService.UpdateStockByStockIdRequest1 request);
        
        // CODEGEN: Generating message contract since the operation UpdateStockByStockSellerCode is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        N11Lib.ProductStockService.UpdateStockByStockSellerCodeResponse1 UpdateStockByStockSellerCode(N11Lib.ProductStockService.UpdateStockByStockSellerCodeRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetProductStockByProductId is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        N11Lib.ProductStockService.GetProductStockByProductIdResponse1 GetProductStockByProductId(N11Lib.ProductStockService.GetProductStockByProductIdRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetProductStockByProductSellerCode is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        N11Lib.ProductStockService.GetProductStockByProductSellerCodeResponse1 GetProductStockByProductSellerCode(N11Lib.ProductStockService.GetProductStockByProductSellerCodeRequest1 request);
        
        // CODEGEN: Generating message contract since the operation IncreaseStockByStockSellerCode is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        N11Lib.ProductStockService.IncreaseStockByStockSellerCodeResponse1 IncreaseStockByStockSellerCode(N11Lib.ProductStockService.IncreaseStockByStockSellerCodeRequest1 request);
        
        // CODEGEN: Generating message contract since the operation IncreaseStockByStockAttributes is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        N11Lib.ProductStockService.IncreaseStockByStockAttributesResponse1 IncreaseStockByStockAttributes(N11Lib.ProductStockService.IncreaseStockByStockAttributesRequest1 request);
        
        // CODEGEN: Generating message contract since the operation IncreaseStockByStockId is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        N11Lib.ProductStockService.IncreaseStockByStockIdResponse1 IncreaseStockByStockId(N11Lib.ProductStockService.IncreaseStockByStockIdRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class DeleteAndUpdateStockByStockAttributesRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private ProductWithIdAndStockAttributesForUpdate productField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ProductWithIdAndStockAttributesForUpdate product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
                this.RaisePropertyChanged("product");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class Authentication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string appKeyField;
        
        private string appSecretField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string appKey {
            get {
                return this.appKeyField;
            }
            set {
                this.appKeyField = value;
                this.RaisePropertyChanged("appKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string appSecret {
            get {
                return this.appSecretField;
            }
            set {
                this.appSecretField = value;
                this.RaisePropertyChanged("appSecret");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class StockItemForAddStockWithId : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string quantityToIncreaseField;
        
        private long versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=1)]
        public string quantityToIncrease {
            get {
                return this.quantityToIncreaseField;
            }
            set {
                this.quantityToIncreaseField = value;
                this.RaisePropertyChanged("quantityToIncrease");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class StockItemForAddStockWithAttributes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StockAttribute[] attributesField;
        
        private string quantityToIncreaseField;
        
        private long versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("attribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockAttribute[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
                this.RaisePropertyChanged("attributes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=1)]
        public string quantityToIncrease {
            get {
                return this.quantityToIncreaseField;
            }
            set {
                this.quantityToIncreaseField = value;
                this.RaisePropertyChanged("quantityToIncrease");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class StockAttribute : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ProductWithIdAndStockAttributes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private StockItemForAddStockWithAttributes[] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockItemForAddStockWithAttributes[] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
                this.RaisePropertyChanged("stockItems");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class StockItemForAddStockWithSellerStockCode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sellerStockCodeField;
        
        private string quantityToIncreaseField;
        
        private long versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sellerStockCode {
            get {
                return this.sellerStockCodeField;
            }
            set {
                this.sellerStockCodeField = value;
                this.RaisePropertyChanged("sellerStockCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=1)]
        public string quantityToIncrease {
            get {
                return this.quantityToIncreaseField;
            }
            set {
                this.quantityToIncreaseField = value;
                this.RaisePropertyChanged("quantityToIncrease");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ProductAttribute : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ProductSku : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private long versionField;
        
        private string quantityField;
        
        private string sellerStockCodeField;
        
        private ProductAttribute[] attributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=2)]
        public string quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string sellerStockCode {
            get {
                return this.sellerStockCodeField;
            }
            set {
                this.sellerStockCodeField = value;
                this.RaisePropertyChanged("sellerStockCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("attribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ProductAttribute[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
                this.RaisePropertyChanged("attributes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class StockItemForUpdateStockWithSellerStockCode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sellerStockCodeField;
        
        private string quantityField;
        
        private long versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sellerStockCode {
            get {
                return this.sellerStockCodeField;
            }
            set {
                this.sellerStockCodeField = value;
                this.RaisePropertyChanged("sellerStockCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=1)]
        public string quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class StockItemForUpdateStockWithId : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string quantityField;
        
        private long versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=1)]
        public string quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class StockItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ResultInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private string errorCategoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string errorCategory {
            get {
                return this.errorCategoryField;
            }
            set {
                this.errorCategoryField = value;
                this.RaisePropertyChanged("errorCategory");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class StockItemForUpdateStockWithAttributes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StockAttribute[] attributesField;
        
        private string quantityField;
        
        private long versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("attribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockAttribute[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
                this.RaisePropertyChanged("attributes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=1)]
        public string quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ProductWithIdAndStockAttributesForUpdate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private StockItemForUpdateStockWithAttributes[] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockItemForUpdateStockWithAttributes[] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
                this.RaisePropertyChanged("stockItems");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class DeleteAndUpdateStockByStockAttributesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private StockItem[][] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", typeof(StockItem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockItem[][] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
                this.RaisePropertyChanged("stockItems");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteAndUpdateStockByStockAttributesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public N11Lib.ProductStockService.DeleteAndUpdateStockByStockAttributesRequest DeleteAndUpdateStockByStockAttributesRequest;
        
        public DeleteAndUpdateStockByStockAttributesRequest1() {
        }
        
        public DeleteAndUpdateStockByStockAttributesRequest1(N11Lib.ProductStockService.DeleteAndUpdateStockByStockAttributesRequest DeleteAndUpdateStockByStockAttributesRequest) {
            this.DeleteAndUpdateStockByStockAttributesRequest = DeleteAndUpdateStockByStockAttributesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteAndUpdateStockByStockAttributesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public N11Lib.ProductStockService.DeleteAndUpdateStockByStockAttributesResponse DeleteAndUpdateStockByStockAttributesResponse;
        
        public DeleteAndUpdateStockByStockAttributesResponse1() {
        }
        
        public DeleteAndUpdateStockByStockAttributesResponse1(N11Lib.ProductStockService.DeleteAndUpdateStockByStockAttributesResponse DeleteAndUpdateStockByStockAttributesResponse) {
            this.DeleteAndUpdateStockByStockAttributesResponse = DeleteAndUpdateStockByStockAttributesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class UpdateStockByStockIdRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private StockItemForUpdateStockWithId[] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockItemForUpdateStockWithId[] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
                this.RaisePropertyChanged("stockItems");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class UpdateStockByStockIdResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private StockItem[][] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", typeof(StockItem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockItem[][] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
                this.RaisePropertyChanged("stockItems");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStockByStockIdRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public N11Lib.ProductStockService.UpdateStockByStockIdRequest UpdateStockByStockIdRequest;
        
        public UpdateStockByStockIdRequest1() {
        }
        
        public UpdateStockByStockIdRequest1(N11Lib.ProductStockService.UpdateStockByStockIdRequest UpdateStockByStockIdRequest) {
            this.UpdateStockByStockIdRequest = UpdateStockByStockIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStockByStockIdResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public N11Lib.ProductStockService.UpdateStockByStockIdResponse UpdateStockByStockIdResponse;
        
        public UpdateStockByStockIdResponse1() {
        }
        
        public UpdateStockByStockIdResponse1(N11Lib.ProductStockService.UpdateStockByStockIdResponse UpdateStockByStockIdResponse) {
            this.UpdateStockByStockIdResponse = UpdateStockByStockIdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class UpdateStockByStockSellerCodeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private StockItemForUpdateStockWithSellerStockCode[] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockItemForUpdateStockWithSellerStockCode[] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
                this.RaisePropertyChanged("stockItems");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class UpdateStockByStockSellerCodeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private StockItem[][] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", typeof(StockItem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockItem[][] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
                this.RaisePropertyChanged("stockItems");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStockByStockSellerCodeRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public N11Lib.ProductStockService.UpdateStockByStockSellerCodeRequest UpdateStockByStockSellerCodeRequest;
        
        public UpdateStockByStockSellerCodeRequest1() {
        }
        
        public UpdateStockByStockSellerCodeRequest1(N11Lib.ProductStockService.UpdateStockByStockSellerCodeRequest UpdateStockByStockSellerCodeRequest) {
            this.UpdateStockByStockSellerCodeRequest = UpdateStockByStockSellerCodeRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStockByStockSellerCodeResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public N11Lib.ProductStockService.UpdateStockByStockSellerCodeResponse UpdateStockByStockSellerCodeResponse;
        
        public UpdateStockByStockSellerCodeResponse1() {
        }
        
        public UpdateStockByStockSellerCodeResponse1(N11Lib.ProductStockService.UpdateStockByStockSellerCodeResponse UpdateStockByStockSellerCodeResponse) {
            this.UpdateStockByStockSellerCodeResponse = UpdateStockByStockSellerCodeResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetProductStockByProductIdRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private long productIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetProductStockByProductIdResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private ProductSku[] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ProductSku[] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
                this.RaisePropertyChanged("stockItems");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductStockByProductIdRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public N11Lib.ProductStockService.GetProductStockByProductIdRequest GetProductStockByProductIdRequest;
        
        public GetProductStockByProductIdRequest1() {
        }
        
        public GetProductStockByProductIdRequest1(N11Lib.ProductStockService.GetProductStockByProductIdRequest GetProductStockByProductIdRequest) {
            this.GetProductStockByProductIdRequest = GetProductStockByProductIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductStockByProductIdResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public N11Lib.ProductStockService.GetProductStockByProductIdResponse GetProductStockByProductIdResponse;
        
        public GetProductStockByProductIdResponse1() {
        }
        
        public GetProductStockByProductIdResponse1(N11Lib.ProductStockService.GetProductStockByProductIdResponse GetProductStockByProductIdResponse) {
            this.GetProductStockByProductIdResponse = GetProductStockByProductIdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetProductStockByProductSellerCodeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private string productSellerCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string productSellerCode {
            get {
                return this.productSellerCodeField;
            }
            set {
                this.productSellerCodeField = value;
                this.RaisePropertyChanged("productSellerCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetProductStockByProductSellerCodeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private ProductSku[] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ProductSku[] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
                this.RaisePropertyChanged("stockItems");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductStockByProductSellerCodeRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public N11Lib.ProductStockService.GetProductStockByProductSellerCodeRequest GetProductStockByProductSellerCodeRequest;
        
        public GetProductStockByProductSellerCodeRequest1() {
        }
        
        public GetProductStockByProductSellerCodeRequest1(N11Lib.ProductStockService.GetProductStockByProductSellerCodeRequest GetProductStockByProductSellerCodeRequest) {
            this.GetProductStockByProductSellerCodeRequest = GetProductStockByProductSellerCodeRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductStockByProductSellerCodeResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public N11Lib.ProductStockService.GetProductStockByProductSellerCodeResponse GetProductStockByProductSellerCodeResponse;
        
        public GetProductStockByProductSellerCodeResponse1() {
        }
        
        public GetProductStockByProductSellerCodeResponse1(N11Lib.ProductStockService.GetProductStockByProductSellerCodeResponse GetProductStockByProductSellerCodeResponse) {
            this.GetProductStockByProductSellerCodeResponse = GetProductStockByProductSellerCodeResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class IncreaseStockByStockSellerCodeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private StockItemForAddStockWithSellerStockCode[] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockItemForAddStockWithSellerStockCode[] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
                this.RaisePropertyChanged("stockItems");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class IncreaseStockByStockSellerCodeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private StockItem[][] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", typeof(StockItem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockItem[][] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
                this.RaisePropertyChanged("stockItems");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IncreaseStockByStockSellerCodeRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public N11Lib.ProductStockService.IncreaseStockByStockSellerCodeRequest IncreaseStockByStockSellerCodeRequest;
        
        public IncreaseStockByStockSellerCodeRequest1() {
        }
        
        public IncreaseStockByStockSellerCodeRequest1(N11Lib.ProductStockService.IncreaseStockByStockSellerCodeRequest IncreaseStockByStockSellerCodeRequest) {
            this.IncreaseStockByStockSellerCodeRequest = IncreaseStockByStockSellerCodeRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IncreaseStockByStockSellerCodeResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public N11Lib.ProductStockService.IncreaseStockByStockSellerCodeResponse IncreaseStockByStockSellerCodeResponse;
        
        public IncreaseStockByStockSellerCodeResponse1() {
        }
        
        public IncreaseStockByStockSellerCodeResponse1(N11Lib.ProductStockService.IncreaseStockByStockSellerCodeResponse IncreaseStockByStockSellerCodeResponse) {
            this.IncreaseStockByStockSellerCodeResponse = IncreaseStockByStockSellerCodeResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class IncreaseStockByStockAttributesRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private ProductWithIdAndStockAttributes productField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ProductWithIdAndStockAttributes product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
                this.RaisePropertyChanged("product");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class IncreaseStockByStockAttributesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private StockItem[][] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", typeof(StockItem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockItem[][] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
                this.RaisePropertyChanged("stockItems");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IncreaseStockByStockAttributesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public N11Lib.ProductStockService.IncreaseStockByStockAttributesRequest IncreaseStockByStockAttributesRequest;
        
        public IncreaseStockByStockAttributesRequest1() {
        }
        
        public IncreaseStockByStockAttributesRequest1(N11Lib.ProductStockService.IncreaseStockByStockAttributesRequest IncreaseStockByStockAttributesRequest) {
            this.IncreaseStockByStockAttributesRequest = IncreaseStockByStockAttributesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IncreaseStockByStockAttributesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public N11Lib.ProductStockService.IncreaseStockByStockAttributesResponse IncreaseStockByStockAttributesResponse;
        
        public IncreaseStockByStockAttributesResponse1() {
        }
        
        public IncreaseStockByStockAttributesResponse1(N11Lib.ProductStockService.IncreaseStockByStockAttributesResponse IncreaseStockByStockAttributesResponse) {
            this.IncreaseStockByStockAttributesResponse = IncreaseStockByStockAttributesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class IncreaseStockByStockIdRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private StockItemForAddStockWithId[] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockItemForAddStockWithId[] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
                this.RaisePropertyChanged("stockItems");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class IncreaseStockByStockIdResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private StockItem[][] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", typeof(StockItem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockItem[][] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
                this.RaisePropertyChanged("stockItems");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IncreaseStockByStockIdRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public N11Lib.ProductStockService.IncreaseStockByStockIdRequest IncreaseStockByStockIdRequest;
        
        public IncreaseStockByStockIdRequest1() {
        }
        
        public IncreaseStockByStockIdRequest1(N11Lib.ProductStockService.IncreaseStockByStockIdRequest IncreaseStockByStockIdRequest) {
            this.IncreaseStockByStockIdRequest = IncreaseStockByStockIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IncreaseStockByStockIdResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public N11Lib.ProductStockService.IncreaseStockByStockIdResponse IncreaseStockByStockIdResponse;
        
        public IncreaseStockByStockIdResponse1() {
        }
        
        public IncreaseStockByStockIdResponse1(N11Lib.ProductStockService.IncreaseStockByStockIdResponse IncreaseStockByStockIdResponse) {
            this.IncreaseStockByStockIdResponse = IncreaseStockByStockIdResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductStockServicePortChannel : N11Lib.ProductStockService.ProductStockServicePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductStockServicePortClient : System.ServiceModel.ClientBase<N11Lib.ProductStockService.ProductStockServicePort>, N11Lib.ProductStockService.ProductStockServicePort {
        
        public ProductStockServicePortClient() {
        }
        
        public ProductStockServicePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductStockServicePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductStockServicePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductStockServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        N11Lib.ProductStockService.DeleteAndUpdateStockByStockAttributesResponse1 N11Lib.ProductStockService.ProductStockServicePort.DeleteAndUpdateStockByStockAttributes(N11Lib.ProductStockService.DeleteAndUpdateStockByStockAttributesRequest1 request) {
            return base.Channel.DeleteAndUpdateStockByStockAttributes(request);
        }
        
        public N11Lib.ProductStockService.DeleteAndUpdateStockByStockAttributesResponse DeleteAndUpdateStockByStockAttributes(N11Lib.ProductStockService.DeleteAndUpdateStockByStockAttributesRequest DeleteAndUpdateStockByStockAttributesRequest) {
            N11Lib.ProductStockService.DeleteAndUpdateStockByStockAttributesRequest1 inValue = new N11Lib.ProductStockService.DeleteAndUpdateStockByStockAttributesRequest1();
            inValue.DeleteAndUpdateStockByStockAttributesRequest = DeleteAndUpdateStockByStockAttributesRequest;
            N11Lib.ProductStockService.DeleteAndUpdateStockByStockAttributesResponse1 retVal = ((N11Lib.ProductStockService.ProductStockServicePort)(this)).DeleteAndUpdateStockByStockAttributes(inValue);
            return retVal.DeleteAndUpdateStockByStockAttributesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        N11Lib.ProductStockService.UpdateStockByStockIdResponse1 N11Lib.ProductStockService.ProductStockServicePort.UpdateStockByStockId(N11Lib.ProductStockService.UpdateStockByStockIdRequest1 request) {
            return base.Channel.UpdateStockByStockId(request);
        }
        
        public N11Lib.ProductStockService.UpdateStockByStockIdResponse UpdateStockByStockId(N11Lib.ProductStockService.UpdateStockByStockIdRequest UpdateStockByStockIdRequest) {
            N11Lib.ProductStockService.UpdateStockByStockIdRequest1 inValue = new N11Lib.ProductStockService.UpdateStockByStockIdRequest1();
            inValue.UpdateStockByStockIdRequest = UpdateStockByStockIdRequest;
            N11Lib.ProductStockService.UpdateStockByStockIdResponse1 retVal = ((N11Lib.ProductStockService.ProductStockServicePort)(this)).UpdateStockByStockId(inValue);
            return retVal.UpdateStockByStockIdResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        N11Lib.ProductStockService.UpdateStockByStockSellerCodeResponse1 N11Lib.ProductStockService.ProductStockServicePort.UpdateStockByStockSellerCode(N11Lib.ProductStockService.UpdateStockByStockSellerCodeRequest1 request) {
            return base.Channel.UpdateStockByStockSellerCode(request);
        }
        
        public N11Lib.ProductStockService.UpdateStockByStockSellerCodeResponse UpdateStockByStockSellerCode(N11Lib.ProductStockService.UpdateStockByStockSellerCodeRequest UpdateStockByStockSellerCodeRequest) {
            N11Lib.ProductStockService.UpdateStockByStockSellerCodeRequest1 inValue = new N11Lib.ProductStockService.UpdateStockByStockSellerCodeRequest1();
            inValue.UpdateStockByStockSellerCodeRequest = UpdateStockByStockSellerCodeRequest;
            N11Lib.ProductStockService.UpdateStockByStockSellerCodeResponse1 retVal = ((N11Lib.ProductStockService.ProductStockServicePort)(this)).UpdateStockByStockSellerCode(inValue);
            return retVal.UpdateStockByStockSellerCodeResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        N11Lib.ProductStockService.GetProductStockByProductIdResponse1 N11Lib.ProductStockService.ProductStockServicePort.GetProductStockByProductId(N11Lib.ProductStockService.GetProductStockByProductIdRequest1 request) {
            return base.Channel.GetProductStockByProductId(request);
        }
        
        public N11Lib.ProductStockService.GetProductStockByProductIdResponse GetProductStockByProductId(N11Lib.ProductStockService.GetProductStockByProductIdRequest GetProductStockByProductIdRequest) {
            N11Lib.ProductStockService.GetProductStockByProductIdRequest1 inValue = new N11Lib.ProductStockService.GetProductStockByProductIdRequest1();
            inValue.GetProductStockByProductIdRequest = GetProductStockByProductIdRequest;
            N11Lib.ProductStockService.GetProductStockByProductIdResponse1 retVal = ((N11Lib.ProductStockService.ProductStockServicePort)(this)).GetProductStockByProductId(inValue);
            return retVal.GetProductStockByProductIdResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        N11Lib.ProductStockService.GetProductStockByProductSellerCodeResponse1 N11Lib.ProductStockService.ProductStockServicePort.GetProductStockByProductSellerCode(N11Lib.ProductStockService.GetProductStockByProductSellerCodeRequest1 request) {
            return base.Channel.GetProductStockByProductSellerCode(request);
        }
        
        public N11Lib.ProductStockService.GetProductStockByProductSellerCodeResponse GetProductStockByProductSellerCode(N11Lib.ProductStockService.GetProductStockByProductSellerCodeRequest GetProductStockByProductSellerCodeRequest) {
            N11Lib.ProductStockService.GetProductStockByProductSellerCodeRequest1 inValue = new N11Lib.ProductStockService.GetProductStockByProductSellerCodeRequest1();
            inValue.GetProductStockByProductSellerCodeRequest = GetProductStockByProductSellerCodeRequest;
            N11Lib.ProductStockService.GetProductStockByProductSellerCodeResponse1 retVal = ((N11Lib.ProductStockService.ProductStockServicePort)(this)).GetProductStockByProductSellerCode(inValue);
            return retVal.GetProductStockByProductSellerCodeResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        N11Lib.ProductStockService.IncreaseStockByStockSellerCodeResponse1 N11Lib.ProductStockService.ProductStockServicePort.IncreaseStockByStockSellerCode(N11Lib.ProductStockService.IncreaseStockByStockSellerCodeRequest1 request) {
            return base.Channel.IncreaseStockByStockSellerCode(request);
        }
        
        public N11Lib.ProductStockService.IncreaseStockByStockSellerCodeResponse IncreaseStockByStockSellerCode(N11Lib.ProductStockService.IncreaseStockByStockSellerCodeRequest IncreaseStockByStockSellerCodeRequest) {
            N11Lib.ProductStockService.IncreaseStockByStockSellerCodeRequest1 inValue = new N11Lib.ProductStockService.IncreaseStockByStockSellerCodeRequest1();
            inValue.IncreaseStockByStockSellerCodeRequest = IncreaseStockByStockSellerCodeRequest;
            N11Lib.ProductStockService.IncreaseStockByStockSellerCodeResponse1 retVal = ((N11Lib.ProductStockService.ProductStockServicePort)(this)).IncreaseStockByStockSellerCode(inValue);
            return retVal.IncreaseStockByStockSellerCodeResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        N11Lib.ProductStockService.IncreaseStockByStockAttributesResponse1 N11Lib.ProductStockService.ProductStockServicePort.IncreaseStockByStockAttributes(N11Lib.ProductStockService.IncreaseStockByStockAttributesRequest1 request) {
            return base.Channel.IncreaseStockByStockAttributes(request);
        }
        
        public N11Lib.ProductStockService.IncreaseStockByStockAttributesResponse IncreaseStockByStockAttributes(N11Lib.ProductStockService.IncreaseStockByStockAttributesRequest IncreaseStockByStockAttributesRequest) {
            N11Lib.ProductStockService.IncreaseStockByStockAttributesRequest1 inValue = new N11Lib.ProductStockService.IncreaseStockByStockAttributesRequest1();
            inValue.IncreaseStockByStockAttributesRequest = IncreaseStockByStockAttributesRequest;
            N11Lib.ProductStockService.IncreaseStockByStockAttributesResponse1 retVal = ((N11Lib.ProductStockService.ProductStockServicePort)(this)).IncreaseStockByStockAttributes(inValue);
            return retVal.IncreaseStockByStockAttributesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        N11Lib.ProductStockService.IncreaseStockByStockIdResponse1 N11Lib.ProductStockService.ProductStockServicePort.IncreaseStockByStockId(N11Lib.ProductStockService.IncreaseStockByStockIdRequest1 request) {
            return base.Channel.IncreaseStockByStockId(request);
        }
        
        public N11Lib.ProductStockService.IncreaseStockByStockIdResponse IncreaseStockByStockId(N11Lib.ProductStockService.IncreaseStockByStockIdRequest IncreaseStockByStockIdRequest) {
            N11Lib.ProductStockService.IncreaseStockByStockIdRequest1 inValue = new N11Lib.ProductStockService.IncreaseStockByStockIdRequest1();
            inValue.IncreaseStockByStockIdRequest = IncreaseStockByStockIdRequest;
            N11Lib.ProductStockService.IncreaseStockByStockIdResponse1 retVal = ((N11Lib.ProductStockService.ProductStockServicePort)(this)).IncreaseStockByStockId(inValue);
            return retVal.IncreaseStockByStockIdResponse;
        }
    }
}
