// <auto-generated />
namespace StorMan.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class LocalCategoryLevels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LocalCategoryLevels));
        
        string IMigrationMetadata.Id
        {
            get { return "201306131507432_LocalCategoryLevels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
