
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StorMan.Data
{
    
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
    
        public Attribute()
        {
    
            this.AttributeValues = new HashSet<AttributeValue>();
    
            this.Categories = new HashSet<Category>();
    
        }
    
    
        public int ID { get; set; }
    
        public string Name { get; set; }
    
        public bool IsMandatory { get; set; }
    
        public bool IsMultipleSelect { get; set; }
    
    
    
        public virtual ICollection<AttributeValue> AttributeValues { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
    
    }

}
