//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorMan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.LocalCategories = new HashSet<LocalCategory>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public System.DateTime CrDate { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
    
        public virtual ICollection<LocalCategory> LocalCategories { get; set; }
    }
}
