
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StorMan.Data
{
    
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryMap
    {
    
        public int ID { get; set; }
    
        public int CategoryID { get; set; }
    
        public string Level1 { get; set; }
    
        public string Level2 { get; set; }
    
        public string Level3 { get; set; }
    
        public string Level4 { get; set; }
    
        public string Level5 { get; set; }
    
        public Nullable<System.DateTime> CrDate { get; set; }
    
        public Nullable<System.DateTime> UpdDate { get; set; }
    
    
    
        public virtual Category Category { get; set; }
    
    }

}
