
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StorMan.Data
{
    
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeRate
    {
    
        public int ID { get; set; }
    
        public string FromCurrency { get; set; }
    
        public string ToCurrency { get; set; }
    
        public decimal Rate { get; set; }
    
    }

}
