//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorMan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalCategories
    {
        public LocalCategories()
        {
            this.LocalCategories1 = new HashSet<LocalCategories>();
            this.Categories = new HashSet<Categories>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public string ParentCategory_Code { get; set; }
    
        public virtual ICollection<LocalCategories> LocalCategories1 { get; set; }
        public virtual LocalCategories LocalCategories2 { get; set; }
        public virtual ICollection<Categories> Categories { get; set; }
    }
}
