

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StorMan.Data
{
    
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    
    public partial class StorManEntities : DbContext
    {
        public StorManEntities()
            : base("name=StorManEntities")
        {
    
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public DbSet<Attribute> Attributes { get; set; }
    
        public DbSet<AttributeValue> AttributeValues { get; set; }
    
        public DbSet<Category> Categories { get; set; }
    
        public DbSet<ConvertedDataSet> ConvertedDataSets { get; set; }
    
        public DbSet<ConvertedDataSetHistory> ConvertedDataSetHistories { get; set; }
    
        public DbSet<ExchangeRate> ExchangeRates { get; set; }
    
        public DbSet<Filter> Filters { get; set; }
    
        public DbSet<LocalCategory> LocalCategories { get; set; }
    
        public DbSet<Operation> Operations { get; set; }
    
        public DbSet<Transform> Transforms { get; set; }
    
    }

}

