
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StorMan.Data
{
    
    using System;
    using System.Collections.Generic;
    
    public partial class Transform
    {
    
        public Transform()
        {
    
            this.Filters = new HashSet<Filter>();
    
            this.Operations = new HashSet<Operation>();
    
        }
    
    
        public int ID { get; set; }
    
        public int ConvertedDataSetID { get; set; }
    
        public string Name { get; set; }
    
    
    
        public virtual ConvertedDataSet ConvertedDataSet { get; set; }
    
        public virtual ICollection<Filter> Filters { get; set; }
    
        public virtual ICollection<Operation> Operations { get; set; }
    
    }

}
